/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category Pay
 * @category generated
 */
export type PayInstructionArgs = {
  amount: beet.bignum
  decimals: number
}
/**
 * @category Instructions
 * @category Pay
 * @category generated
 */
export const payStruct = new beet.BeetArgsStruct<
  PayInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', beet.u64],
    ['decimals', beet.u8],
  ],
  'PayInstructionArgs'
)
/**
 * Accounts required by the _pay_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [] mint
 * @property [_writable_] buyerVault
 * @property [_writable_] sellerVault
 * @property [] index
 * @category Instructions
 * @category Pay
 * @category generated
 */
export type PayInstructionAccounts = {
  signer: web3.PublicKey
  mint: web3.PublicKey
  buyerVault: web3.PublicKey
  sellerVault: web3.PublicKey
  tokenProgram?: web3.PublicKey
  index: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const payInstructionDiscriminator = [
  119, 18, 216, 65, 192, 117, 122, 220,
]

/**
 * Creates a _Pay_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Pay
 * @category generated
 */
export function createPayInstruction(
  accounts: PayInstructionAccounts,
  args: PayInstructionArgs,
  programId = new web3.PublicKey('payrbiNjqzWNBC41QtE3iUF7UbMjNfekUQbZjaauhVC')
) {
  const [data] = payStruct.serialize({
    instructionDiscriminator: payInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.sellerVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.index,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
