/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AcceptRequest
 * @category generated
 */
export const acceptRequestStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'AcceptRequestInstructionArgs',
)
/**
 * Accounts required by the _acceptRequest_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @category Instructions
 * @category AcceptRequest
 * @category generated
 */
export type AcceptRequestInstructionAccounts = {
  signer: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const acceptRequestInstructionDiscriminator = [
  4, 60, 28, 227, 25, 199, 246, 124,
]

/**
 * Creates a _AcceptRequest_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category AcceptRequest
 * @category generated
 */
export function createAcceptRequestInstruction(
  accounts: AcceptRequestInstructionAccounts,
  programId = new web3.PublicKey(
    'E6E7kfSE21wnKrpvtEQsCj3XFnZyeXu6UjoLcjogqbLQ',
  ),
) {
  const [data] = acceptRequestStruct.serialize({
    instructionDiscriminator: acceptRequestInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
