/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category DenyRequest
 * @category generated
 */
export const denyRequestStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'DenyRequestInstructionArgs',
)
/**
 * Accounts required by the _denyRequest_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @category Instructions
 * @category DenyRequest
 * @category generated
 */
export type DenyRequestInstructionAccounts = {
  signer: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const denyRequestInstructionDiscriminator = [
  143, 236, 238, 188, 131, 164, 217, 107,
]

/**
 * Creates a _DenyRequest_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category DenyRequest
 * @category generated
 */
export function createDenyRequestInstruction(
  accounts: DenyRequestInstructionAccounts,
  programId = new web3.PublicKey(
    'E6E7kfSE21wnKrpvtEQsCj3XFnZyeXu6UjoLcjogqbLQ',
  ),
) {
  const [data] = denyRequestStruct.serialize({
    instructionDiscriminator: denyRequestInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
