/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category DoRequest
 * @category generated
 */
export const doRequestStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'DoRequestInstructionArgs',
)
/**
 * Accounts required by the _doRequest_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @category Instructions
 * @category DoRequest
 * @category generated
 */
export type DoRequestInstructionAccounts = {
  signer: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const doRequestInstructionDiscriminator = [
  134, 2, 68, 124, 245, 169, 186, 82,
]

/**
 * Creates a _DoRequest_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category DoRequest
 * @category generated
 */
export function createDoRequestInstruction(
  accounts: DoRequestInstructionAccounts,
  programId = new web3.PublicKey(
    'BHQvQgoMZhCKuVeoVhsy8agZQYwMuvzXwrEYoEHHDgGJ',
  ),
) {
  const [data] = doRequestStruct.serialize({
    instructionDiscriminator: doRequestInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
