/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InitNetwork
 * @category generated
 */
export type InitNetworkInstructionArgs = {
  proposalCollectionUri: string
}
/**
 * @category Instructions
 * @category InitNetwork
 * @category generated
 */
export const initNetworkStruct = new beet.FixableBeetArgsStruct<
  InitNetworkInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['proposalCollectionUri', beet.utf8String],
  ],
  'InitNetworkInstructionArgs',
)
/**
 * Accounts required by the _initNetwork_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] network
 * @property [_writable_] networkMint
 * @property [_writable_] councilCollection
 * @property [_writable_] serviceCollection
 * @property [_writable_] proposalCollection
 * @property [_writable_] proposalCollectionVault
 * @property [_writable_] proposalMetadata
 * @property [_writable_] proposalCollectionMasterEdition
 * @property [] associatedTokenProgram
 * @property [] tokenMetadataProgram
 * @category Instructions
 * @category InitNetwork
 * @category generated
 */
export type InitNetworkInstructionAccounts = {
  signer: web3.PublicKey
  network: web3.PublicKey
  networkMint: web3.PublicKey
  councilCollection: web3.PublicKey
  serviceCollection: web3.PublicKey
  proposalCollection: web3.PublicKey
  proposalCollectionVault: web3.PublicKey
  proposalMetadata: web3.PublicKey
  proposalCollectionMasterEdition: web3.PublicKey
  rent?: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  tokenMetadataProgram: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initNetworkInstructionDiscriminator = [
  104, 231, 73, 121, 240, 0, 5, 148,
]

/**
 * Creates a _InitNetwork_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitNetwork
 * @category generated
 */
export function createInitNetworkInstruction(
  accounts: InitNetworkInstructionAccounts,
  args: InitNetworkInstructionArgs,
  programId = new web3.PublicKey(
    'BHQvQgoMZhCKuVeoVhsy8agZQYwMuvzXwrEYoEHHDgGJ',
  ),
) {
  const [data] = initNetworkStruct.serialize({
    instructionDiscriminator: initNetworkInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.network,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.networkMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.councilCollection,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.serviceCollection,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalCollection,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalCollectionVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalCollectionMasterEdition,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMetadataProgram,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
