/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type InitProposalParams = {
  id: number[] /* size: 16 */
  name: string
  description: string
  proposalUri: string
}

/**
 * @category userTypes
 * @category generated
 */
export const initProposalParamsBeet =
  new beet.FixableBeetArgsStruct<InitProposalParams>(
    [
      ['id', beet.uniformFixedSizeArray(beet.u8, 16)],
      ['name', beet.utf8String],
      ['description', beet.utf8String],
      ['proposalUri', beet.utf8String],
    ],
    'InitProposalParams',
  )
