/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RegisterBuyFungible
 * @category generated
 */
export type RegisterBuyFungibleInstructionArgs = {
  amount: number
}
/**
 * @category Instructions
 * @category RegisterBuyFungible
 * @category generated
 */
export const registerBuyFungibleStruct = new beet.BeetArgsStruct<
  RegisterBuyFungibleInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', beet.u32],
  ],
  'RegisterBuyFungibleInstructionArgs'
)
/**
 * Accounts required by the _registerBuyFungible_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] seller (optional)
 * @property [_writable_] marketplaceAuth (optional)
 * @property [_writable_] marketplace
 * @property [_writable_] product
 * @property [_writable_] productMint
 * @property [] paymentMint
 * @property [_writable_] buyerTokenVault
 * @property [_writable_] buyerTransferVault (optional)
 * @property [_writable_] sellerTransferVault (optional)
 * @property [_writable_] marketplaceTransferVault (optional)
 * @property [_writable_] bountyVault (optional)
 * @property [_writable_] sellerReward (optional)
 * @property [_writable_] sellerRewardVault (optional)
 * @property [_writable_] buyerReward (optional)
 * @property [_writable_] buyerRewardVault (optional)
 * @category Instructions
 * @category RegisterBuyFungible
 * @category generated
 */
export type RegisterBuyFungibleInstructionAccounts = {
  signer: web3.PublicKey
  seller?: web3.PublicKey
  marketplaceAuth?: web3.PublicKey
  marketplace: web3.PublicKey
  product: web3.PublicKey
  productMint: web3.PublicKey
  paymentMint: web3.PublicKey
  buyerTokenVault: web3.PublicKey
  buyerTransferVault?: web3.PublicKey
  sellerTransferVault?: web3.PublicKey
  marketplaceTransferVault?: web3.PublicKey
  bountyVault?: web3.PublicKey
  sellerReward?: web3.PublicKey
  sellerRewardVault?: web3.PublicKey
  buyerReward?: web3.PublicKey
  buyerRewardVault?: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const registerBuyFungibleInstructionDiscriminator = [
  39, 74, 167, 144, 209, 210, 85, 3,
]

/**
 * Creates a _RegisterBuyFungible_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RegisterBuyFungible
 * @category generated
 */
export function createRegisterBuyFungibleInstruction(
  accounts: RegisterBuyFungibleInstructionAccounts,
  args: RegisterBuyFungibleInstructionArgs,
  programId = new web3.PublicKey('brick5uEiJqSkfuAvMtKmq7kiuEVmbjVMiigyV51GRF')
) {
  const [data] = registerBuyFungibleStruct.serialize({
    instructionDiscriminator: registerBuyFungibleInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.seller ?? programId,
      isWritable: accounts.seller != null,
      isSigner: false,
    },
    {
      pubkey: accounts.marketplaceAuth ?? programId,
      isWritable: accounts.marketplaceAuth != null,
      isSigner: false,
    },
    {
      pubkey: accounts.marketplace,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.product,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.productMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.paymentMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerTokenVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerTransferVault ?? programId,
      isWritable: accounts.buyerTransferVault != null,
      isSigner: false,
    },
    {
      pubkey: accounts.sellerTransferVault ?? programId,
      isWritable: accounts.sellerTransferVault != null,
      isSigner: false,
    },
    {
      pubkey: accounts.marketplaceTransferVault ?? programId,
      isWritable: accounts.marketplaceTransferVault != null,
      isSigner: false,
    },
    {
      pubkey: accounts.bountyVault ?? programId,
      isWritable: accounts.bountyVault != null,
      isSigner: false,
    },
    {
      pubkey: accounts.sellerReward ?? programId,
      isWritable: accounts.sellerReward != null,
      isSigner: false,
    },
    {
      pubkey: accounts.sellerRewardVault ?? programId,
      isWritable: accounts.sellerRewardVault != null,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerReward ?? programId,
      isWritable: accounts.buyerReward != null,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerRewardVault ?? programId,
      isWritable: accounts.buyerRewardVault != null,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
