/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * Arguments used to create {@link Network}
 * @category Accounts
 * @category generated
 */
export type NetworkArgs = {
  councilCollection: web3.PublicKey
  serviceCollection: web3.PublicKey
  proposalCollection: web3.PublicKey
  networkMint: web3.PublicKey
  councilCollectionBump: number
  serviceCollectionBump: number
  proposalCollectionBump: number
  mintBump: number
  bump: number
}

export const networkDiscriminator = [51, 5, 209, 183, 60, 99, 156, 251]
/**
 * Holds the data for the {@link Network} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Network implements NetworkArgs {
  private constructor(
    readonly councilCollection: web3.PublicKey,
    readonly serviceCollection: web3.PublicKey,
    readonly proposalCollection: web3.PublicKey,
    readonly networkMint: web3.PublicKey,
    readonly councilCollectionBump: number,
    readonly serviceCollectionBump: number,
    readonly proposalCollectionBump: number,
    readonly mintBump: number,
    readonly bump: number
  ) {}

  /**
   * Creates a {@link Network} instance from the provided args.
   */
  static fromArgs(args: NetworkArgs) {
    return new Network(
      args.councilCollection,
      args.serviceCollection,
      args.proposalCollection,
      args.networkMint,
      args.councilCollectionBump,
      args.serviceCollectionBump,
      args.proposalCollectionBump,
      args.mintBump,
      args.bump
    )
  }

  /**
   * Deserializes the {@link Network} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Network, number] {
    return Network.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Network} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Network> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Network account at ${address}`)
    }
    return Network.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'BHQvQgoMZhCKuVeoVhsy8agZQYwMuvzXwrEYoEHHDgGJ'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, networkBeet)
  }

  /**
   * Deserializes the {@link Network} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Network, number] {
    return networkBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Network} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return networkBeet.serialize({
      accountDiscriminator: networkDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Network}
   */
  static get byteSize() {
    return networkBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Network} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Network.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Network} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Network.byteSize
  }

  /**
   * Returns a readable version of {@link Network} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      councilCollection: this.councilCollection.toBase58(),
      serviceCollection: this.serviceCollection.toBase58(),
      proposalCollection: this.proposalCollection.toBase58(),
      networkMint: this.networkMint.toBase58(),
      councilCollectionBump: this.councilCollectionBump,
      serviceCollectionBump: this.serviceCollectionBump,
      proposalCollectionBump: this.proposalCollectionBump,
      mintBump: this.mintBump,
      bump: this.bump,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const networkBeet = new beet.BeetStruct<
  Network,
  NetworkArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['councilCollection', beetSolana.publicKey],
    ['serviceCollection', beetSolana.publicKey],
    ['proposalCollection', beetSolana.publicKey],
    ['networkMint', beetSolana.publicKey],
    ['councilCollectionBump', beet.u8],
    ['serviceCollectionBump', beet.u8],
    ['proposalCollectionBump', beet.u8],
    ['mintBump', beet.u8],
    ['bump', beet.u8],
  ],
  Network.fromArgs,
  'Network'
)
